### ISSUE TITLE
YAMLException: unknown tag !<!include> 

### ISSUE THREAD

**Issue by CarpeDiemRo** [thomasloven/hass-lovelace_gen#14]
I was using non-yaml Lovelace UI and I was trying to add an !include YAML file. It was unsuccessfully. _YAMLException: unknown tag !<!include>_  message was returned

Furthermore, I switched to the YAML mode of Lovelace and I installed _lovelace_gen_. Unfortunately, the result was the same. 
![Screenshot 2020-05-14 at 12 23 40](https://user-images.githubusercontent.com/38489167/81918046-a9aa2580-95de-11ea-9acb-7238a899bd5f.png)
![Screenshot 2020-05-14 at 12 30 30](https://user-images.githubusercontent.com/38489167/81918130-c6465d80-95de-11ea-99f0-e16a626ad697.png)

What can I do?

**Comment by thomasloven** [comment]
That's a screenshot from the RAW GUI editor - which is disabled in yaml mode.
Did you click the [YAML mode](https://www.home-assistant.io/lovelace/yaml-mode/) link in the readme?

**Comment by CarpeDiemRo** [comment]
Meanwhile I made another configuration and everything works just fine.
