### ISSUE TITLE
Lovelace Gen breaks after upgrading to Home Assistant 2021.4.0

### ISSUE THREAD

**Issue by adizag** [thomasloven/hass-lovelace_gen#27]
just after upgrading to Home Assistant 2021.4.0, I got this message while checking configuration:

> We are now explicitly only supporting secrets inside your Home Assistant Core and Lovelace configuration files (and anything included from there). Secrets are no longer supported in other loaded YAML files.

I noticed that there is a breaking change announcement but could understand what is to be done in order to solve it:

> **Secrets**
> At this moment, we are unsure if this is a breaking change or not, so we list it, just to be sure.
> 
> We are now explicitly only supporting secrets inside your Home Assistant Core and Lovelace configuration files (and anything included from there). Secrets are no longer supported in other loaded YAML files.
> 
> This change should not affect regular users of Home Assistant, however, we have been made aware that some custom integrations may cause problems. If you are a user of Dwains theme, the HomeKit Infused theme or **lovelace_gen**, please make sure to update those or check with the upstream project.

I have no idea what to do.
tnx.

**Comment by crnh** [comment]
I encountered the same issue and solved it by replacing `__init__.py` with the version from this repo. It does contain changes that solved the issue (at least for me).

**Comment by adizag** [comment]
@crnh I guess such a change in files should have given an update alert through HACS. but I didn't get any.

**Comment by crnh** [comment]
Yes, there is no new release yet (which is required to make HACS show a new version). I don't know if the changed code will work for everybody, but for me this turned out to be a good temporary solution.

**Comment by adizag** [comment]
@crnh worked for me too.
tnx!
