### ISSUE TITLE
lovelace_gen and labels not working

### ISSUE THREAD

**Issue by WallyDW** [thomasloven/hass-lovelace_gen#63]
it seems that labels might not be working in lovelace_gen.

This works:
```
# lovelace_gen
type: markdown
content: >-
  {% raw %}
    {{ label_entities("esphome") }}
  {% endraw %}
```

and this works:
```
# lovelace_gen
{% set updates ='test' %}
type: markdown
content: >-
  {{ updates }}
```

but this does not:
```
# lovelace_gen
{% set updates = label_entities('esphome') %}
type: markdown
content: >-
  {{ updates }}
```

Is there another way to extract labels on entities in lovelace_gen?

**Comment by WallyDW** [comment]
And btw. the link to YAML mode in the installation instructions link to a 404 page.

**Comment by WallyDW** [comment]
Okay, it seems that lovelace_gen have no access to the state machine in HA when it is parsing the YAML, so I made a work around.
I have now set Node Red to extract the entity names I need and then store them in a file that is included as global variables in lovelace_gen.
This part work as I can now make a markdown card and write out the entity names.

The problem here is that the {% raw %} does not seem to work inside other yaml code, so this is seems not possible.
```
type: markdown
content:
  {%- for e in _global.entity_list -%}
    {%- raw -%}
      {{ state_attr('
    {%- endraw -%}
    {{ e }}
    {%- raw -%}
      ','friendly_name') }}
    {%- endraw -%}
  {%- endfor -%}
```

**Comment by WallyDW** [comment]
Seems like comments are parsed too.

# lovelace_gen

This does not work:
```
type: markdown
content: 
  {% for e in _global.entity_list %}
    {%- raw -%}
      "{{- state_attr('
    {%- endraw -%}
        {{ e }}
    {%- raw -%}
      ','friendly_name') -}}"
    {%- endraw -%}
  {% endfor %}
```

Commenting out lines does not work either:
```
type: markdown
content: 
  {% for e in _global.entity_list %}
#    {%- raw -%}
#      "{{- state_attr('
#    {%- endraw -%}
        {{ e }}
#    {%- raw -%}
#      ','friendly_name') -}}"
#    {%- endraw -%}
  {% endfor %}
```

Deleting the lines commented out does however work:
```
type: markdown
content: 
  {% for e in _global.entity_list %}
        {{ e }}
  {% endfor %}
```

**Comment by WallyDW** [comment]
I got lucky and used a custom button card that showed the actual parsed code when there was an error in the YAML code.
It showed that the brackets with - did not always remove line breaks and sometimes even removed spaces at times.
This seems to work.
```
type: markdown
content: >
  {% for e in _global.entity_list %}
    "{%- raw -%}{{- state_attr('{%- endraw -%}{{ e }}{%- raw -%}','friendly_name') -}}{%- endraw -%}"
  {% endfor %}
```
When on one line the - on brackets can usually be removed.
When on multiple lines the - should be used on raw section brackets, but not brackets outside the raw section.

I hope this helps others to get it working. :)

**Comment by skavan** [comment]
Hi,
Can you explain what the dashes do in {%- raw -%} and the like?
For others, one thing I have found useful (through trial and error) is cleaning up the raw/endraw mess with macros.
example:
```
{% macro get_attribute(entity_id, attribute) %}
  {% set local_entity_id = entity_id %}
  {% raw %} {{ state_attr({% endraw %}'{{ entity_id }}', '{{ attribute }}'{% raw %}) }} {% endraw %}
{% endmacro %}
```
and then used by:
```
- type: custom:mushroom-template-card
  primary: "{{ get_attribute(media_player_entity, 'friendly_name') }}"
  secondary: "{{ get_attribute(media_player_entity, 'source') }}"
  icon: mdi:home
```
I would imagine we could create a library of macros and import them, to enjoy the benefits of lovelace_gen and regular templating with less pain.

Please let me know if there are better ways -- I'm just trying to wrap my head around all this!

**Comment by WallyDW** [comment]
The dash will remove a newline either before a {{ or {% or after a %} or }}

Let us say you want to show a date with a leading zero, but the sensor you have just contains the integer value, which is without a leading zero.

You would have to use if-then to put the 0 in front, like
'''
{% if (states('sensor.datevalue')<10) %}
  0
{% endif %}
{{ ('sensor.datevalue') }}

If the integer value is 5, then this looks like it should give you 05 as out put, but instead it will give you this output.

0
5

Because there is a line break inside the if-then value line.

Changing the endif line to {%- endif %} will remove the newline after the 0 and the output will be 05 then.

It is a general Jinja notation, so not something special for lovelace_gen.
